server:
  port: 8888  # 项目的端口号
  servlet:
    context-path: /warehouse   # 上下文路径，所有请求路径前面必须添加此路径
spring:
  mvc:
    pathmatch: # 重要！否则会报错
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://123.249.102.245:26000/mydb?useUnicode=true&characterEncoding=UTF-8&sererTimezone=Asia/Shanghai&schema_name=ticketmanager&ApplicationName=app
    username: palewave
    password: MyDB@123
    druid:
      initial-size: 5 # 初始化连接数
      max-active: 30  # 最大连接数
      min-idle: 3     # 最小空闲数
      max-wait: 4000  # 超时时间，单位：毫秒



mybatis:
  type-aliases-package: com.wk.warehouse.entity # 给实体类起别名，别名就是类名
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # role_id -> roleId

swagger:
  enabled: true
  title: 测试接口
  description: 描述测试接口
  version: 1.0.0
  contact:
    name: Peter He
    url:
    email: 2585866229@qq.com
  package: com.program.test.myTest
  base-path: /**
  exclude-path: /error, /ops/**
